### ISSUE TITLE
Develop Question class

### ISSUE THREAD

**Issue by Slaviator** [Slaviator/TestOfKnowledgeMVC#7]
@Slaviator

**Comment by Slaviator** [comment]
@sevr1k check it, don't close the issue early, leave it in testing.

**Comment by Slaviator** [comment]
Id property left with an idea to haw a QuestionsContext and reuse them. Should be discussed
@sevr1k

**Comment by Slaviator** [comment]
@sevr1k KISS principle, no id, no question contexts for now

**Comment by sevr1k** [comment]
@Slaviator Id its important for this table. All users in future can leave comment for questions, so we need this id. KISS principle say "do everything easily", so i think we need add id for all tables.

**Comment by Slaviator** [comment]
@sevr1k added id 8aacf9db

**Comment by FilipVoloshin** [comment]
991be16a
